uvicorn:
  host: "0.0.0.0"
  port: 8000
  log_level: "debug"
logs:
  path: "logs"
predict:
  path: "data/to_predict.csv"
  model_path: "models"
prepare:
  digits: 100000
  path: "data/to_predict.csv"
